### ISSUE TITLE
Difference between code and paper fomula about classAvg

### ISSUE THREAD

**Issue by SunnyWuYang** [haqishen/MFNet-pytorch#3]
I'm confused about `conf[:,cid] = cf[:,cid]/cf[:,cid].sum()`  in  `calculate_result()` function(util.py).
In this paper and other papers, the definition of class accuracy is: $\frac{P_{ii}}{\sum_{j} P_{ij}$, 
in this way, the code should be `conf[cid,:] = cf[cid,:]/cf[cid,:].sum()`

**Comment by yuxiangsun** [comment]
> I'm confused about `conf[:,cid] = cf[:,cid]/cf[:,cid].sum()` in `calculate_result()` function(util.py).
> In this paper and other papers, the definition of class accuracy is: $\frac{P_{ii}}{\sum_{j} P_{ij}$,
> in this way, the code should be `conf[cid,:] = cf[cid,:]/cf[cid,:].sum()`

You can refer to this repo for the metric code.

https://github.com/yuxiangsun/RTFNet/blob/master/util/util.py

**Comment by SunnyWuYang** [comment]
Thanks for your reply! However, in RTFNet, the metrics are precision_per_class, recall_per_class and iou_per_class, do not have class accuracy.
